name: craftalism

services:

  postgres:
    image: postgres:18
    container_name: craftalism-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: craftalism
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

    networks:
      - craftalism-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d craftalism"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: craftalism-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/craftalism
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - craftalism-network
    restart: on-failure

volumes:
  pgdata:

networks:
  craftalism-network:
